name: Run Scraper

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

on:
  schedule:
    - cron: '0 6,14,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m spacy download de_core_news_sm

    - name: Run Scraper
      run: python scraper/scrape.py

    - name: Commit updated DB
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git pull --rebase
        if [ -f db/razzien.db ]; then
          git add db/razzien.db
          git commit -m "Update DB" || echo "No changes to commit"
          git push
        else
          echo "No database found to commit."
        fi
